theme: jekyll-theme-minimal
title: Alfarizqi Wira Anadyar
description: Information Systems Student | Data Analyst & Local LLM Enthusiast
show_downloads: true
logo: https://github.com/vangguard10/alfarizqi-portofolio/blob/main/IMG_1163.png
